services:

  # Asql heavy load
  asql:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.asql
    container_name: asql-app
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      internal:
        ipv4_address: 10.10.10.2
    restart: unless-stopped

  # UI server frontend
  streamlit:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.streamlit
    container_name: asql-streamlit
    environment:
      - APP_URL=http://asql:8080
      - HOME=/app
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      internal:
        ipv4_address: 10.10.10.3
    restart: unless-stopped
    depends_on:
      - asql
    volumes:
    - streamlit:/home/streamlit

  # reverse proxy 
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:alpine
    container_name: asql-caddy
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-""}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${CADDYFILE:-Caddyfile.dev}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_certs:/etc/caddy/certs
    networks:
      internal:
        ipv4_address: 10.10.10.4
      public:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    depends_on:
      - streamlit

volumes:
  caddy_data:
  caddy_certs:
  streamlit:

networks:

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.10.10.0/29

  public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
