package parser

func (s *stackParser) ddl_expr() *parseErr {
	return nil
}

// DDL_EXPR        := CREATE TABLE IDENTIFIER ( TABLE_BODY )
// TABLE_BODY      := (COLUMN_DEF | CONSTRAINT_DEF) { , (COLUMN_DEF | CONSTRAINT_DEF) }
// COLUMN_DEF      := IDENTIFIER DATA_TYPE [ NULLABILITY ]
// DATA_TYPE       := NUMERIC_TYPE | CHAR_TYPE | DATE
// NUMERIC_TYPE    := NUMERIC ( INTEGER [ , INTEGER ] )
// CHAR_TYPE       := CHAR ( INTEGER )
// NULLABILITY     := NOT NULL | NULL
// CONSTRAINT_DEF  := CONSTRAINT IDENTIFIER CONSTRAINT_TYPE
// CONSTRAINT_TYPE := PRIMARY KEY ( COL_LIST )
//                  | FOREIGN KEY IDENTIFIER ( COL_LIST ) REFERENCES IDENTIFIER ( COL_LIST )
//                  | CHECK ( CONDITION )
// COL_LIST        := IDENTIFIER { , IDENTIFIER }
